name: Build mdbook
description: Build mdbook documentation with Docker and caching

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

    - name: Build with Docker
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        target: ci-builder
        tags: mdbook-builder:latest
        load: true
        cache-from: type=gha,scope=mdbook
        cache-to: type=gha,scope=mdbook,mode=max

    - name: Run build
      shell: bash
      run: |
        docker run --rm -v ${{ github.workspace }}:/data mdbook-builder:latest sh -c "mdbook-mermaid install . && mdbook build"
