name: Build mdbook
description: Build mdbook documentation with Docker and caching

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Build with Docker
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        context: .
        target: ci-builder
        tags: mdbook-builder:latest
        load: true
        cache-from: type=gha,scope=mdbook
        cache-to: type=gha,scope=mdbook,mode=max

    - name: Run build
      shell: bash
      run: |
        docker run --rm -v ${{ github.workspace }}:/data mdbook-builder:latest sh -c "mdbook-mermaid install . && mdbook build"
